yolo_model:

  config_file:
    name: yolov4-tiny-custom.cfg
  weight_file:
    name: yolov4-tiny-custom_final.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - blue_cone
      - yellow_cone
      - orange_cone
      - large_orange_cone
